table.insert(data.raw["technology"]["automobilism"].prerequisites,"wheel")
table.insert(data.raw["technology"]["laser-turrets"].effects,{type = "unlock-recipe",recipe = "laser-turret-2"})
table.insert(data.raw["technology"]["laser-turrets"].effects,{type = "unlock-recipe",recipe = "laser-turret-3"})
table.insert(data.raw["technology"]["bullet-damage-1"].effects,{type = "ammo-damage",ammo_category = "sniper-ammo",modifier = "0.1"})
table.insert(data.raw["technology"]["bullet-damage-2"].effects,{type = "ammo-damage",ammo_category = "sniper-ammo",modifier = "0.1"})
table.insert(data.raw["technology"]["bullet-damage-3"].effects,{type = "ammo-damage",ammo_category = "sniper-ammo",modifier = "0.2"})
table.insert(data.raw["technology"]["bullet-damage-4"].effects,{type = "ammo-damage",ammo_category = "sniper-ammo",modifier = "0.2"})
table.insert(data.raw["technology"]["bullet-damage-5"].effects,{type = "ammo-damage",ammo_category = "sniper-ammo",modifier = "0.2"})
table.insert(data.raw["technology"]["bullet-damage-6"].effects,{type = "ammo-damage",ammo_category = "sniper-ammo",modifier = "0.4"})
table.insert(data.raw["technology"]["bullet-speed-1"].effects,{type = "gun-speed",ammo_category = "sniper-ammo",modifier = "0.2"})
table.insert(data.raw["technology"]["bullet-speed-2"].effects,{type = "gun-speed",ammo_category = "sniper-ammo",modifier = "0.2"})
table.insert(data.raw["technology"]["bullet-speed-3"].effects,{type = "gun-speed",ammo_category = "sniper-ammo",modifier = "0.3"})
table.insert(data.raw["technology"]["bullet-speed-4"].effects,{type = "gun-speed",ammo_category = "sniper-ammo",modifier = "0.3"})
table.insert(data.raw["technology"]["bullet-speed-5"].effects,{type = "gun-speed",ammo_category = "sniper-ammo",modifier = "0.3"})
table.insert(data.raw["technology"]["bullet-speed-6"].effects,{type = "gun-speed",ammo_category = "sniper-ammo",modifier = "0.3"})
table.insert(data.raw["technology"]["automated-rail-transportation"].effects,{type = "unlock-recipe",recipe = "cargo-wagon-large"})
table.insert(data.raw["technology"]["solar-energy"].effects,{type = "unlock-recipe",recipe = "solar-panel-secondary"})
table.insert(data.raw["technology"]["solar-energy"].effects,{type = "unlock-recipe",recipe = "solar-panel-terciary"})
table.insert(data.raw["technology"]["electric-energy-accumulators-1"].effects,{type = "unlock-recipe",recipe = "basic-accumulator-primary"})
table.insert(data.raw["technology"]["electric-energy-accumulators-1"].effects,{type = "unlock-recipe",recipe = "basic-accumulator-secondary"})