data:extend(
{
  {
    type = "fluid",
    name = "molten-copper",
    default_temperature = 1000,
    max_temperature = 1000,
    heat_capacity = "0KJ",
    base_color = {r=214, g=165, b=91},
    flow_color = {r=214, g=165, b=91},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/molten-copper.png",
    order = "copper",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	max_to_push = 1.5,
	ratio_to_push = 3.15,
    subgroup = "metallurgy-fluid-metal-basic",
  },
  {
    type = "fluid",
    name = "molten-iron",
    default_temperature = 1400,
    max_temperature = 1400,
    heat_capacity = "0KJ",
    base_color = {r=185, g=188, b=192},
    flow_color = {r=185, g=188, b=192},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/molten-iron.png",
    order = "iron",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	max_to_push = 1.5,
	ratio_to_push = 3.15,
    subgroup = "metallurgy-fluid-metal-basic",
  },
  {
    type = "fluid",
    name = "molten-carbonated-iron",
    default_temperature = 1900,
    max_temperature = 1900,
    heat_capacity = "0KJ",
    base_color = {r=185, g=188, b=192},
    flow_color = {r=185, g=188, b=192},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/molten-carbonated-iron.png",
    order = "carbonated-iron",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	max_to_push = 1.5,
	ratio_to_push = 3.15,
    subgroup = "metallurgy-fluid-metal-basic",
  },
  {
    type = "fluid",
    name = "molten-tin",
    default_temperature = 400,
    max_temperature = 400,
    heat_capacity = "0KJ",
    base_color = {r=214, g=165, b=91},
    flow_color = {r=214, g=165, b=91},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/molten-tin.png",
    order = "tin",
    pressure_to_speed_ratio = 0.2,
    flow_to_energy_ratio = 0.295,
	max_to_push = 1.5,
	ratio_to_push = 3.15,
    subgroup = "metallurgy-fluid-metal-basic",
  },
  {
    type = "fluid",
    name = "molten-zinc",
    default_temperature = 500,
    max_temperature = 500,
    heat_capacity = "0KJ",
    base_color = {r=214, g=165, b=91},
    flow_color = {r=214, g=165, b=91},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/molten-zinc.png",
    order = "zinc",
    pressure_to_speed_ratio = 0.2,
    flow_to_energy_ratio = 0.295,
	max_to_push = 1.5,
	ratio_to_push = 3.15,
    subgroup = "metallurgy-fluid-metal-basic",
  },
  {
    type = "fluid",
    name = "molten-lead",
    default_temperature = 400,
    max_temperature = 400,
    heat_capacity = "0KJ",
    base_color = {r=214, g=165, b=91},
    flow_color = {r=214, g=165, b=91},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/molten-lead.png",
    order = "lead",
    pressure_to_speed_ratio = 0.2,
    flow_to_energy_ratio = 0.295,
	max_to_push = 1.5,
	ratio_to_push = 3.15,
    subgroup = "metallurgy-fluid-metal-basic",
  },
  {
    type = "fluid",
    name = "molten-silver",
    default_temperature = 2200,
    max_temperature = 2200,
    heat_capacity = "0KJ",
    base_color = {r=214, g=165, b=91},
    flow_color = {r=214, g=165, b=91},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/molten-silver.png",
    order = "silver",
    pressure_to_speed_ratio = 0.2,
    flow_to_energy_ratio = 0.295,
	max_to_push = 1.5,
	ratio_to_push = 3.15,
    subgroup = "metallurgy-fluid-metal-basic",
  },
  {
    type = "fluid",
    name = "molten-gold",
    default_temperature = 1100,
    max_temperature = 1100,
    heat_capacity = "0KJ",
    base_color = {r=214, g=165, b=91},
    flow_color = {r=214, g=165, b=91},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/molten-gold.png",
    order = "gold",
    pressure_to_speed_ratio = 0.2,
    flow_to_energy_ratio = 0.295,
	max_to_push = 1.5,
	ratio_to_push = 3.15,
    subgroup = "metallurgy-fluid-metal-basic",
  },
  {
    type = "fluid",
    name = "molten-tungsten",
    default_temperature = 3500,
    max_temperature = 3500,
    heat_capacity = "0KJ",
    base_color = {r=214, g=165, b=91},
    flow_color = {r=214, g=165, b=91},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/molten-tungsten.png",
    order = "tungsten",
    pressure_to_speed_ratio = 0.2,
    flow_to_energy_ratio = 0.295,
	max_to_push = 1.5,
	ratio_to_push = 3.15,
    subgroup = "metallurgy-fluid-metal-basic",
  },
  {
    type = "fluid",
    name = "molten-ardite",
    default_temperature = 1700,
    max_temperature = 1700,
    heat_capacity = "0KJ",
    base_color = {r=214, g=165, b=91},
    flow_color = {r=214, g=165, b=91},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/molten-ardite.png",
    order = "ardite",
    pressure_to_speed_ratio = 0.2,
    flow_to_energy_ratio = 0.295,
	max_to_push = 1.5,
	ratio_to_push = 3.15,
    subgroup = "metallurgy-fluid-metal-basic",
  },
  {
    type = "fluid",
    name = "molten-cobalt",
    default_temperature = 2500,
    max_temperature = 2500,
    heat_capacity = "0KJ",
    base_color = {r=214, g=165, b=91},
    flow_color = {r=214, g=165, b=91},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/molten-cobalt.png",
    order = "cobalt",
    pressure_to_speed_ratio = 0.2,
    flow_to_energy_ratio = 0.295,
	max_to_push = 1.5,
	ratio_to_push = 3.15,
    subgroup = "metallurgy-fluid-metal-basic",
  },
}
)