data:extend(
{
  {
	type= "item",
	name= "gem-collector",
	icon= "__DyTech-Storage__/graphics/icons/gem-collector.png",
	flags= {"goes-to-quickbar"},
	subgroup = "collector",
	order= "c-g",
	place_result= "gem-collector",
	stack_size= 10,
  },
  {
	type= "item",
	name= "stone-collector",
	icon= "__DyTech-Storage__/graphics/icons/stone-collector.png",
	flags= {"goes-to-quickbar"},
	subgroup = "collector",
	order= "c-s",
	place_result= "stone-collector",
	stack_size= 10,
  },
  {
	type= "item",
	name= "sand-collector",
	icon= "__DyTech-Storage__/graphics/icons/sand-collector.png",
	flags= {"goes-to-quickbar"},
	subgroup = "collector",
	order= "c-s",
	place_result= "sand-collector",
	stack_size= 10,
  },
  {
	type= "item",
	name= "coal-collector",
	icon= "__DyTech-Storage__/graphics/icons/coal-collector.png",
	flags= {"goes-to-quickbar"},
	subgroup = "collector",
	order= "c-c",
	place_result= "coal-collector",
	stack_size= 10,
  },
  {
	type= "item",
	name= "stone-collector-1",
	icon= "__DyTech-Storage__/graphics/icons/stone-collector.png",
	flags= {"goes-to-quickbar"},
	subgroup = "collector",
	order= "c-s",
	place_result= "stone-collector-1",
	stack_size= 10,
  },
  {
	type= "item",
	name= "sand-collector-1",
	icon= "__DyTech-Storage__/graphics/icons/sand-collector.png",
	flags= {"goes-to-quickbar"},
	subgroup = "collector",
	order= "c-s",
	place_result= "sand-collector-1",
	stack_size= 10,
  },
  {
	type= "item",
	name= "coal-collector-1",
	icon= "__DyTech-Storage__/graphics/icons/coal-collector.png",
	flags= {"goes-to-quickbar"},
	subgroup = "collector",
	order= "c-c",
	place_result= "coal-collector-1",
	stack_size= 10,
  },
}
)