require("prototypes.entity.units")
require("prototypes.entity.units-corpses")
require("prototypes.entity.units-spawner")
require("prototypes.entity.units-spawner-corpses")
require("prototypes.item.units-spawner")
require("prototypes.recipe.units-spawner")