require("prototypes.entity.collector")
require("prototypes.item.collector")
require("prototypes.recipe.collector")
require("prototypes.entity.robot")
require("prototypes.item.robot")
require("prototypes.recipe.robot")
require("prototypes.technology.robot")