module("BuildDatabase")

--  [""]={},
--  [""]={resource=1}, =,

--[[CRAFTED ITEMS]]--

craftitems =
{
	-- Base Game Items --
	["wooden-chest"]={chest=1},
	["stone-furnace"]={machine=1},
	["boiler"]={machine=1, energy=1},
	["steam-engine"]={machine=1, energy=1},
	["basic-transport-belt"]={belt=1},
	["basic-mining-drill"]={mining=2, machine=1, resource=65},
	["burner-mining-drill"]={mining=1, machine=1, resource=32.5},
	["basic-inserter"]={inserter=1},
	["burner-inserter"]={inserter=1},
	["pipe"]={pipes=1},
	["offshore-pump"]={machine=1, tech=1},
	["small-electric-pole"]={energy=1},
	["radar"]={machine=1},
	["small-lamp"]={machine=1, energy=1},
	["pipe-to-ground"]={pipes=1},
	["assembling-machine-1"]={machine=1},
	["gun-turret"]={turret=1},
	["laser-turret"]={turret=2},
	["long-handed-inserter"]={inserter=1},
	["fast-inserter"]={inserter=1},
	["smart-inserter"]={inserter=1, tech=1},
	["player-port"]={machine=1},
	["fast-transport-belt"]={belt=2},
	["express-transport-belt"]={belt=3},
	["solar-panel"]={energy=3, machine=1},
	["assembling-machine-2"]={machine=2},
	["assembling-machine-3"]={machine=3},
	["car"]={transport=1},
	["straight-rail"]={transport=1},
	["curved-rail"]={transport=4},
	["diesel-locomotive"]={transport=2},
	["cargo-wagon"]={transport=2},
	["train-stop"]={transport=1, tech=1},
	["rail-signal"]={transport=1, tech=1},
	["iron-chest"]={chest=1},
	["steel-chest"]={chest=1},
	["smart-chest"]={chest=1, tech=1},
	["wall"]={walls=1, resource=5},
	["land-mine"]={ammo=1},
	["lab"]={machine=1, science=1},
	["red-wire"]={tech=1},
	["green-wire"]={tech=1},
	["basic-transport-belt-to-ground"]={belt=1},
	["fast-transport-belt-to-ground"]={belt=2},
	["express-transport-belt-to-ground"]={belt=3},
	["basic-splitter"]={belt=1, tech=1},
	["fast-splitter"]={belt=2, tech=2},
	["express-splitter"]={belt=3, tech=3},
	["logistic-robot"]={robot=1, tech=1},
	["construction-robot"]={robot=1, tech=1},
	["logistic-chest-passive-provider"]={robot=1, chest=1},
	["logistic-chest-active-provider"]={robot=1, chest=1},
	["logistic-chest-requester"]={robot=1, chest=1},
	["logistic-chest-storage"]={robot=1, chest=1},
	["rocket-defense"]={machine=1000, tech=1000},
	["roboport"]={robot=5, machine=1},
	["big-electric-pole"]={energy=3},
	["substation"]={energy=5},
	["medium-electric-pole"]={energy=2},
	["basic-accumulator"]={energy=25, tech=1},
	["steel-furnace"]={energy=1, machine=1, resource=10},
	["electric-furnace"]={energy=3, resource=10, machine=1},
	["basic-beacon"]={machine=1},
	["pumpjack"]={machine=1, tech=1},
	["oil-refinery"]={machine=1, resource=10},
	["storage-tank"]={machine=1},
	["small-pump"]={energy=1, machine=1},
	["chemical-plant"]={machine=1, resource=10},
	-- DyTech Core --
	["rubber-seed"]={resource=1},
	["dytech-item-collector"]={resource=1, tech=10},
	["liquid-handler"]={machine=1},
	["sandwall"]={walls=1},
	-- DyTech Automation --
	["basic-mining-drill-mk2"]={mining=4, resource=125, machine=1},
	["basic-mining-drill-mk3"]={mining=8, resource=250, machine=1},
	["basic-mining-drill-mk4"]={mining=16, resource=500, machine=1},
	["basic-mining-drill-mk5"]={mining=32, resource=1000, machine=1},
	["basic-mining-drill-mk6"]={mining=100, resource=10000, machine=1},
	["steel-furnace-mk2"]={machine=2, energy=2, resource=20},
	["steel-furnace-mk3"]={machine=3, energy=3, resource=30},
	["steel-furnace-mk4"]={machine=4, energy=4, resource=40},
	["steel-furnace-mk5"]={machine=5, energy=5, resource=50},
	["electric-furnace-mk2"]={machine=2, energy=2, resource=20},
	["electric-furnace-mk3"]={machine=3, energy=3, resource=30},
	["electric-furnace-mk4"]={machine=4, energy=4, resource=40},
	["electric-furnace-mk5"]={machine=5, energy=5, resource=50},
	["assembling-machine-4"]={machine=4},
	["assembling-machine-5"]={machine=5},
	["assembling-machine-6"]={machine=6},
	["assembling-machine-7"]={machine=7},
	["radar-mk2"]={machine=2},
	["radar-mk3"]={machine=3},
	["radar-mk4"]={machine=4},
	["radar-mk5"]={machine=5},
	-- DyTech Compatibility --
	-- DyTech Dynamic --
	-- DyTech Energy --
	["boiler-mk2"]={energy=1, machine=1},
	["boiler-mk3"]={energy=1, machine=1},
	["boiler-mk4"]={energy=1, machine=1},
	["boiler-mk5"]={energy=1, machine=1},
	["small-pump-mk2"]={energy=1},
	["small-pump-mk3"]={energy=1},
	["small-pump-mk4"]={energy=1},
	["small-pump-mk5"]={energy=1},
	["pipe-mk2"]={pipes=2},
	["pipe-mk3"]={pipes=3},
	["pipe-mk4"]={pipes=4},
	["pipe-mk5"]={pipes=5},
	["pipe-to-ground-mk2"]={pipes=2},
	["pipe-to-ground-mk3"]={pipes=3},
	["pipe-to-ground-mk4"]={pipes=4},
	["pipe-to-ground-mk5"]={pipes=5},
	["steam-engine-primary"]={machine=1, energy=1},
	["steam-engine-primary-mk2"]={energy=1, machine=1},
	["steam-engine-primary-mk3"]={energy=1, machine=1},
	["steam-engine-primary-mk4"]={energy=1, machine=1},
	["steam-engine-primary-mk5"]={energy=1, machine=1},
	["steam-engine-secondary-mk2"]={energy=1, machine=1},
	["steam-engine-secondary-mk3"]={energy=1, machine=1},
	["steam-engine-secondary-mk4"]={energy=1, machine=1},
	["steam-engine-secondary-mk5"]={energy=1, machine=1},
	["steam-engine-terciary"]={machine=1, energy=1},
	["steam-engine-terciary-mk2"]={energy=1, machine=1},
	["steam-engine-terciary-mk3"]={energy=1, machine=1},
	["steam-engine-terciary-mk4"]={energy=1, machine=1},
	["steam-engine-terciary-mk5"]={energy=1, machine=1},
	["solar-panel-secondary"]={energy=1, machine=1},
	["solar-panel-primary-mk2"]={energy=1, machine=1},
	["solar-panel-secondary-mk2"]={energy=1, machine=1},
	["solar-panel-primary-mk3"]={energy=1, machine=1},
	["solar-panel-secondary-mk3"]={energy=1, machine=1},
	["solar-panel-primary-mk4"]={energy=1, machine=1},
	["solar-panel-secondary-mk4"]={energy=1, machine=1},
	["solar-panel-primary-mk5"]={energy=1, machine=1},
	["solar-panel-secondary-mk5"]={energy=1, machine=1},
	["basic-accumulator-mk2"]={energy=5, machine=1},
	["basic-accumulator-mk3"]={energy=5, machine=1},
	["basic-accumulator-mk4"]={energy=10, machine=1},
	["basic-accumulator-mk5"]={energy=10, machine=1},
	["basic-accumulator-mk6"]={energy=50, machine=1},
	["offshore-pump-mk2"]={machine=1, energy=1},
	["offshore-pump-mk3"]={machine=1, energy=1},
	["offshore-pump-mk4"]={machine=1, energy=1},
	["offshore-pump-mk5"]={machine=1, energy=1},
	-- DyTech Genetics --
	["dog-lair"]={alien=1},
	-- DyTech Inserters --
	["inserter-half"]={inserter=1},
	["inserter-long"]={inserter=2},
	["inserter-half-long"]={inserter=2},
	["inserter-fast-half"]={inserter=2},
	["inserter-veryfast"]={inserter=2},
	["inserter-veryfast-half"]={inserter=2},
	["inserter-half-filter"]={inserter=3},
	["inserter-long-filter"]={inserter=3},
	["inserter-long-half-filter"]={inserter=3},
	["inserter-fast-half-filter"]={inserter=3},
	["inserter-veryfast-filter"]={inserter=3},
	["inserter-veryfast-half-filter"]={inserter=3},
	["inserter-half-smart"]={inserter=4},
	["inserter-long-smart"]={inserter=4},
	["inserter-long-half-smart"]={inserter=4},
	["inserter-fast-half-smart"]={inserter=4},
	["inserter-veryfast-smart"]={inserter=4},
	["inserter-veryfast-half-smart"]={inserter=4},
	["dytech-inserter"]={inserter=5},
	["dytech-inserter-fast"]={inserter=6},
	["long-handed-inserter-filter"]={inserter=1},
	-- DyTech Logistic --
	["logistic-robot-1"]={robot=1},
	["logistic-robot-2"]={robot=1},
	["logistic-chest-passive-provider-1"]={robot=1},
	["logistic-chest-passive-provider-2"]={robot=1},
	["logistic-chest-active-provider-1"]={robot=1},
	["logistic-chest-active-provider-2"]={robot=1},
	["logistic-chest-storage-1"]={robot=1},
	["logistic-chest-storage-2"]={robot=1},
	["logistic-chest-requester-1"]={robot=1},
	["logistic-chest-requester-2"]={robot=1},
	["roboport-1"]={machine=1},
	["roboport-2"]={machine=1},
	["construction-robot-1"]={robot=1},
	["construction-robot-2"]={robot=1},
	["stone-collector"]={chest=1, robot=1},
	["sand-collector"]={chest=1, robot=1},
	["coal-collector"]={chest=1, robot=1},
	-- DyTech Metallurgy --
	["pipe-mainline"]={energy=1, machine=1},
	["pump-to-mainline"]={energy=1, machine=1},
	["pump-from-mainline"]={energy=1, machine=1},
	["pump-inline-mainline"]={energy=1, machine=1},
	["blast-furnace"]={resource=150, machine=1, energy=5},
	["forge"]={plates=50, machine=1},
	["centrifuge"]={machine=1},
	["geothermal-extractor"]={machine=1, mining=1},
	["brickwall"]={walls=1},
	["tungsten-wall"]={walls=1},
	-- DyTech Meteors --
	-- DyTech Modules --
	-- DyTech Storage --
	["stone-collector-1"]={chest=1},
	["sand-collector-1"]={chest=1},
	["coal-collector-1"]={chest=1},
	["wooden-chest-medium"]={chest=7},
	["wooden-chest-big"]={chest=9},
	["steel-chest-medium"]={chest=4},
	["steel-chest-big"]={chest=9},
	["iron-chest-medium"]={chest=4},
	["iron-chest-big"]={chest=9},
	["smart-chest-medium"]={chest=4, tech=1},
	["smart-chest-big"]={chest=9, tech=1},
	["logistic-chest-passive-provider-medium"]={robot=1, chest=4},
	["logistic-chest-passive-provider-big"]={robot=1, chest=9},
	["logistic-chest-active-provider-medium"]={robot=1, chest=4},
	["logistic-chest-active-provider-big"]={robot=1, chest=9},
	["logistic-chest-storage-medium"]={robot=1, chest=4},
	["logistic-chest-storage-big"]={robot=1, chest=9},
	["logistic-chest-requester-medium"]={robot=1, chest=4},
	["logistic-chest-requester-big"]={robot=1, chest=9},
	["storage-tank-2"]={chest=1, energy=1, tech=1},
	["storage-tank-3"]={chest=1, energy=1, tech=1},
	["storage-tank-4"]={chest=1, energy=1, tech=1},
	["storage-tank-5"]={chest=1, energy=1, tech=1},
	-- DyTech Tools --
	-- DyTech Transportation --
	["super-transport-belt"]={belt=4},
	["super-transport-belt-to-ground"]={belt=4},
	["super-splitter"]={belt=4, tech=4},
	["extreme-transport-belt"]={belt=5},
	["extreme-transport-belt-to-ground"]={belt=5},
	["extreme-splitter"]={belt=5, tech=5},
	["car2"]={transport=5, tech=1},
	["diesel-locomotive-armor"]={transport=4, tech=1},
	["diesel-locomotive-fast"]={transport=4, tech=1},
	["cargo-wagon-armor"]={transport=2, tech=1},
	["cargo-wagon-fast"]={transport=2, tech=1},
	["cargo-wagon-large"]={tech=1, transport=5},
	-- DyTech Warfare --
	["gem-crusher"]={machine=1},
	["gem-grinder"]={machine=1},
	["gem-polisher"]={machine=1},
	["compressor"]={machine=1},
	["basic-mining-drill-gem"]={resource=1000, mining=10, machine=10},
	["sniper-turret"]={turret=1},
	["laser-turret-2"]={turret=2},
	["laser-turret-3"]={turret=3},
	["laser-turret-4"]={turret=4},
	["laser-turret-5"]={turret=5},
	["laser-turret-6"]={turret=6},
	["laser-turret-7"]={turret=7},
	["laser-turret-8"]={turret=8},
	["laser-turret-9"]={turret=9},
	["laser-turret-sniper-1"]={turret=10},
	["laser-turret-sniper=2"]={turret=11},
	["laser-turret-sniper=3"]={turret=12},
	["marauder-capsule"]={capsule=1},
	["sharpshooter-capsule"]={capsule=1},
	["frenzy-capsule"]={capsule=1},
	["flame-thrower-turret"]={turret=1},
	["basic-grenade-2"]={capsule=1},
	["basic-grenade-3"]={capsule=1},
}