module("guiNames", package.seeall)

-- Main Dynamics GUI
mainDynamicFrame="mainDynamicFrame"
mainDynamicFlow="mainDynamicFlow"
ResearchButton="ResearchButton"
AutoResearcherButton="AutoResearcherButton"
DynamicToolsButton="DynamicToolsButton"
DynamicPowerButton="DynamicPowerButton"
CollectorsButton="CollectorsButton"
CloseButton="CloseButton"
-- Main Research System GUI
mainResearchFrame="mainResearchFrame"
mainResearchFlow="mainResearchFlow"
mainResearchExtraFrame1="mainResearchExtraFrame1"
mainResearchExtraFrame2="mainResearchExtraFrame2"
mainResearchExtraFrame3="mainResearchExtraFrame3"
mainResearchExtraFrame4="mainResearchExtraFrame4"
mainResearchExtraFrame5="mainResearchExtraFrame5"
mainResearchExtraFrame6="mainResearchExtraFrame6"
mainResearchExtraFlow="mainResearchExtraFlow"
mainLotteryFrame="mainLotteryFrame"
mainLotteryFlow="mainLotteryFlow"
Tier1Base="Tier1Base"
Tier2Base="Tier2Base"
Tier3Base="Tier3Base"
Tier4Base="Tier4Base"
MRSBackButton1="MRSBackButton1"
MRSBackButton2="MRSBackButton2"
-- Table Research System
mainResearchTableFrame="mainResearchTableFrame"
mainResearchTableFlow="mainResearchTableFlow"
RSTable="RSTable"
-- Research System Unlock Screen
mainFrameMRSUnlock="MRSUnlockGUIFrame"
mainFlowMRSUnlock1="MRSUnlockGUIFlow1"
mainFlowMRSUnlock2="MRSUnlockGUIFlow2"
mainFlowMRSUnlock3="MRSUnlockGUIFlow3"
mainFlowMRSUnlock4="MRSUnlockGUIFlow4"
mainFlowMRSUnlock5="MRSUnlockGUIFlow5"
MRSUnlockButton="MRSUnlockButton"
-- Collectors GUI
mainCollectorFrame="mainCollectorFrame"
mainCollectorFlow="mainCollectorFlow"
CollectorWorkingButton="CollectorWorkingButton"
CollectorFilteredButton="CollectorFilteredButton"
CollectorRangeMinusButton="CollectorRangeMinusButton"
CollectorRangeButton="CollectorRangeButton"
CollectorRangePlusButton="CollectorRangePlusButton"
CollectorAutoRangeButton="CollectorAutoRangeButton"
-- Auto Researcher
mainAutoResearcherFlow="mainAutoResearcherFlow"
mainAutoResearcherFrame="mainAutoResearcherFrame"
-- DEBUG
DebugButton1="DebugButton1"