data:extend(
{
  {
	type = "item",
	name = "blast-furnace",
	icon ="__MAIN-DyTech-Machine__/graphics/metallurgy/icons/blast-furnace.png",
	flags = {"goes-to-quickbar"},
	order = "blast-furnace-1",
	place_result = "blast-furnace",
	stack_size = 10,
	subgroup = "dytech-machines-metallurgy",
  },
  {
	type = "item",
	name = "forge",
	icon ="__MAIN-DyTech-Machine__/graphics/metallurgy/icons/forge.png",
	flags = {"goes-to-quickbar"},
	order = "forge-1",
	place_result = "forge",
	stack_size = 10,
	subgroup = "dytech-machines-metallurgy",
  },
  {
	type = "item",
	name = "blast-furnace-1",
	icon ="__MAIN-DyTech-Machine__/graphics/metallurgy/icons/blast-furnace.png",
	flags = {"goes-to-quickbar"},
	order = "blast-furnace-2",
	place_result = "blast-furnace-1",
	stack_size = 10,
	subgroup = "dytech-machines-metallurgy",
  },
  {
	type = "item",
	name = "forge-1",
	icon ="__MAIN-DyTech-Machine__/graphics/metallurgy/icons/forge.png",
	flags = {"goes-to-quickbar"},
	order = "forge-2",
	place_result = "forge-1",
	stack_size = 10,
	subgroup = "dytech-machines-metallurgy",
  },
  {
	type = "item",
	name = "blast-furnace-2",
	icon ="__MAIN-DyTech-Machine__/graphics/metallurgy/icons/blast-furnace.png",
	flags = {"goes-to-quickbar"},
	order = "blast-furnace-3",
	place_result = "blast-furnace-2",
	stack_size = 10,
	subgroup = "dytech-machines-metallurgy",
  },
  {
	type = "item",
	name = "forge-2",
	icon ="__MAIN-DyTech-Machine__/graphics/metallurgy/icons/forge.png",
	flags = {"goes-to-quickbar"},
	order = "forge-3",
	place_result = "forge-2",
	stack_size = 10,
	subgroup = "dytech-machines-metallurgy",
  },
}
)
