data:extend(
{
  {
    type = "fluid",
    name = "lava",
    default_temperature = 500,
    max_temperature = 5000,
    heat_capacity = "600J",
    base_color = {r=254, g=42, b=1},
    flow_color = {r=255, g=79, b=0},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/lava.png",
    order = "lava",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    subgroup = "metallurgy-fluid-lava",
  },
  {
    type = "fluid",
    name = "lava-600",
    default_temperature = 600,
    max_temperature = 5000,
    heat_capacity = "600J",
    base_color = {r=249, g=42, b=1},
    flow_color = {r=250, g=79, b=0},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/lava-600.png",
    order = "lava-0600",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    subgroup = "metallurgy-fluid-lava",
  },
  {
    type = "fluid",
    name = "lava-800",
    default_temperature = 800,
    max_temperature = 5000,
    heat_capacity = "800J",
    base_color = {r=244, g=42, b=1},
    flow_color = {r=245, g=79, b=0},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/lava-800.png",
    order = "lava-0800",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    subgroup = "metallurgy-fluid-lava",
  },
  {
    type = "fluid",
    name = "lava-1000",
    default_temperature = 1000,
    max_temperature = 5000,
    heat_capacity = "1000J",
    base_color = {r=239, g=42, b=1},
    flow_color = {r=240, g=79, b=0},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/lava-1000.png",
    order = "lava-1000",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    subgroup = "metallurgy-fluid-lava",
  },
  {
    type = "fluid",
    name = "lava-1200",
    default_temperature = 1200,
    max_temperature = 5000,
    heat_capacity = "1200J",
    base_color = {r=234, g=42, b=1},
    flow_color = {r=235, g=79, b=0},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/lava-1200.png",
    order = "lava-1200",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    subgroup = "metallurgy-fluid-lava",
  },
  {
    type = "fluid",
    name = "lava-1400",
    default_temperature = 1400,
    max_temperature = 5000,
    heat_capacity = "1400J",
    base_color = {r=229, g=42, b=1},
    flow_color = {r=230, g=79, b=0},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/lava-1400.png",
    order = "lava-1400",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    subgroup = "metallurgy-fluid-lava",
  },
  {
    type = "fluid",
    name = "lava-1600",
    default_temperature = 1600,
    max_temperature = 5000,
    heat_capacity = "1600J",
    base_color = {r=224, g=42, b=1},
    flow_color = {r=225, g=79, b=0},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/lava-1600.png",
    order = "lava-1600",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    subgroup = "metallurgy-fluid-lava",
  },
  {
    type = "fluid",
    name = "lava-1800",
    default_temperature = 1800,
    max_temperature = 5000,
    heat_capacity = "1800J",
    base_color = {r=219, g=42, b=1},
    flow_color = {r=220, g=79, b=0},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/lava-1800.png",
    order = "lava-1800",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    subgroup = "metallurgy-fluid-lava",
  },
  {
    type = "fluid",
    name = "lava-2000",
    default_temperature = 2000,
    max_temperature = 5000,
    heat_capacity = "2000J",
    base_color = {r=214, g=42, b=1},
    flow_color = {r=215, g=79, b=0},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/lava-2000.png",
    order = "lava-2000",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    subgroup = "metallurgy-fluid-lava",
  },
  {
    type = "fluid",
    name = "lava-2200",
    default_temperature = 2200,
    max_temperature = 5000,
    heat_capacity = "2200J",
    base_color = {r=209, g=42, b=1},
    flow_color = {r=210, g=79, b=0},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/lava-2200.png",
    order = "lava-2200",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    subgroup = "metallurgy-fluid-lava",
  },
  {
    type = "fluid",
    name = "lava-2400",
    default_temperature = 2400,
    max_temperature = 5000,
    heat_capacity = "2400J",
    base_color = {r=204, g=42, b=1},
    flow_color = {r=205, g=79, b=0},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/lava-2400.png",
    order = "lava-2400",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    subgroup = "metallurgy-fluid-lava",
  },
  {
    type = "fluid",
    name = "lava-2600",
    default_temperature = 2600,
    max_temperature = 5000,
    heat_capacity = "2600J",
    base_color = {r=199, g=42, b=1},
    flow_color = {r=200, g=79, b=0},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/lava-2600.png",
    order = "lava-2600",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    subgroup = "metallurgy-fluid-lava",
  },
  {
    type = "fluid",
    name = "lava-2800",
    default_temperature = 2800,
    max_temperature = 5000,
    heat_capacity = "2800J",
    base_color = {r=194, g=42, b=1},
    flow_color = {r=195, g=79, b=0},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/lava-2800.png",
    order = "lava-2800",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    subgroup = "metallurgy-fluid-lava",
  },
  {
    type = "fluid",
    name = "lava-3000",
    default_temperature = 3000,
    max_temperature = 5000,
    heat_capacity = "3000J",
    base_color = {r=189, g=42, b=1},
    flow_color = {r=190, g=79, b=0},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/lava-3000.png",
    order = "lava-3000",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    subgroup = "metallurgy-fluid-lava",
  },
  {
    type = "fluid",
    name = "lava-3200",
    default_temperature = 3200,
    max_temperature = 5000,
    heat_capacity = "3200J",
    base_color = {r=184, g=42, b=1},
    flow_color = {r=185, g=79, b=0},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/lava-3200.png",
    order = "lava-3200",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    subgroup = "metallurgy-fluid-lava",
  },
  {
    type = "fluid",
    name = "lava-3400",
    default_temperature = 3400,
    max_temperature = 5000,
    heat_capacity = "3400J",
    base_color = {r=179, g=42, b=1},
    flow_color = {r=180, g=79, b=0},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/lava-3400.png",
    order = "lava-3400",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    subgroup = "metallurgy-fluid-lava",
  },
  {
    type = "fluid",
    name = "lava-3600",
    default_temperature = 3600,
    max_temperature = 5000,
    heat_capacity = "3600J",
    base_color = {r=174, g=42, b=1},
    flow_color = {r=175, g=79, b=0},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/lava-3600.png",
    order = "lava-3600",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    subgroup = "metallurgy-fluid-lava",
  },
  {
    type = "fluid",
    name = "lava-3800",
    default_temperature = 3800,
    max_temperature = 5000,
    heat_capacity = "3800J",
    base_color = {r=169, g=42, b=1},
    flow_color = {r=170, g=79, b=0},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/lava-3800.png",
    order = "lava-3800",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    subgroup = "metallurgy-fluid-lava",
  },
  {
    type = "fluid",
    name = "lava-4000",
    default_temperature = 4000,
    max_temperature = 5000,
    heat_capacity = "4000J",
    base_color = {r=164, g=42, b=1},
    flow_color = {r=165, g=79, b=0},
    icon = "__MAIN-DyTech-Machine__/graphics/metallurgy/fluid/lava-4000.png",
    order = "lava-4000",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    subgroup = "metallurgy-fluid-lava",
  },
}
)