require("prototypes.base-edit.entity")
require("prototypes.base-edit.tech")

require("prototypes.entity.accumulators-large")
require("prototypes.entity.accumulators-normal")
require("prototypes.entity.accumulators-small")
require("prototypes.entity.boiler")
require("prototypes.entity.pipes")
require("prototypes.entity.pipes-to-ground")
require("prototypes.entity.pumps")
require("prototypes.entity.solar-panels-large")
require("prototypes.entity.solar-panels-normal")
require("prototypes.entity.solar-panels-small")
require("prototypes.entity.steam-engines-large")
require("prototypes.entity.steam-engines-normal")
require("prototypes.entity.steam-engines-small")

require("prototypes.item.boiler")
require("prototypes.item.energy-solar-panels")
require("prototypes.item.energy-steam-engines")
require("prototypes.item.pipes")
require("prototypes.item.pipes-to-ground")
require("prototypes.item.pumps")

require("prototypes.recipe.boiler")
require("prototypes.recipe.energy-solar-panels")
require("prototypes.recipe.energy-steam-engines")
require("prototypes.recipe.pipes")
require("prototypes.recipe.pipes-to-ground")
require("prototypes.recipe.pumps")

require("prototypes.technology.energy")