require("prototypes.entity.chest")
require("prototypes.entity.collector")
require("prototypes.entity.logistic-chest")
require("prototypes.entity.tanks")
require("prototypes.item.chest")
require("prototypes.item.collector")
require("prototypes.item.logistic-chest")
require("prototypes.item.tanks")
require("prototypes.recipe.chest")
require("prototypes.recipe.collector")
require("prototypes.recipe.logistic-chest")
require("prototypes.recipe.tanks")
require("prototypes.technology.chest")
require("prototypes.technology.tanks")

data.raw["storage-tank"]["storage-tank"].fast_replaceable_group = "storage-tanks"