data:extend(
{
  {
    type = "fluid",
    name = "lava-600",
    default_temperature = 600,
    max_temperature = 700,
    heat_capacity = "600J",
    base_color = {r=254, g=42, b=1},
    flow_color = {r=255, g=79, b=0},
    icon = "__DyTech-Graphics__/graphics/fluid/lava-600.png",
    order = "lava-1",
    pressure_to_speed_ratio = 0.2,
    flow_to_energy_ratio = 0.295,
    subgroup = "metallurgy-fluid",
  },
  {
    type = "fluid",
    name = "lava-800",
    default_temperature = 800,
    max_temperature = 900,
    heat_capacity = "800J",
    base_color = {r=244, g=42, b=1},
    flow_color = {r=255, g=79, b=0},
    icon = "__DyTech-Graphics__/graphics/fluid/lava-800.png",
    order = "lava-2",
    pressure_to_speed_ratio = 0.2,
    flow_to_energy_ratio = 0.295,
    subgroup = "metallurgy-fluid",
  },
  {
    type = "fluid",
    name = "lava-1000",
    default_temperature = 1000,
    max_temperature = 1100,
    heat_capacity = "1000J",
    base_color = {r=234, g=42, b=1},
    flow_color = {r=255, g=79, b=0},
    icon = "__DyTech-Graphics__/graphics/fluid/lava-1000.png",
    order = "lava-3",
    pressure_to_speed_ratio = 0.2,
    flow_to_energy_ratio = 0.295,
    subgroup = "metallurgy-fluid",
  },
  {
    type = "fluid",
    name = "lava-1200",
    default_temperature = 1200,
    max_temperature = 1300,
    heat_capacity = "1200J",
    base_color = {r=224, g=42, b=1},
    flow_color = {r=255, g=79, b=0},
    icon = "__DyTech-Graphics__/graphics/fluid/lava-1200.png",
    order = "lava-4",
    pressure_to_speed_ratio = 0.2,
    flow_to_energy_ratio = 0.295,
    subgroup = "metallurgy-fluid",
  },
  {
    type = "fluid",
    name = "lava-1400",
    default_temperature = 1400,
    max_temperature = 1500,
    heat_capacity = "1400J",
    base_color = {r=214, g=42, b=1},
    flow_color = {r=255, g=79, b=0},
    icon = "__DyTech-Graphics__/graphics/fluid/lava-1400.png",
    order = "lava-5",
    pressure_to_speed_ratio = 0.2,
    flow_to_energy_ratio = 0.295,
    subgroup = "metallurgy-fluid",
  },
  {
    type = "fluid",
    name = "lava-1600",
    default_temperature = 1600,
    max_temperature = 1700,
    heat_capacity = "1600J",
    base_color = {r=204, g=42, b=1},
    flow_color = {r=255, g=79, b=0},
    icon = "__DyTech-Graphics__/graphics/fluid/lava-1600.png",
    order = "lava-6",
    pressure_to_speed_ratio = 0.2,
    flow_to_energy_ratio = 0.295,
    subgroup = "metallurgy-fluid",
  },
  {
    type = "fluid",
    name = "lava-1800",
    default_temperature = 1800,
    max_temperature = 1900,
    heat_capacity = "1800J",
    base_color = {r=194, g=42, b=1},
    flow_color = {r=255, g=79, b=0},
    icon = "__DyTech-Graphics__/graphics/fluid/lava-1800.png",
    order = "lava-7",
    pressure_to_speed_ratio = 0.2,
    flow_to_energy_ratio = 0.295,
    subgroup = "metallurgy-fluid",
  },
  {
    type = "fluid",
    name = "lava-2000",
    default_temperature = 2000,
    max_temperature = 2100,
    heat_capacity = "2000J",
    base_color = {r=184, g=42, b=1},
    flow_color = {r=255, g=79, b=0},
    icon = "__DyTech-Graphics__/graphics/fluid/lava-2000.png",
    order = "lava-8",
    pressure_to_speed_ratio = 0.2,
    flow_to_energy_ratio = 0.295,
    subgroup = "metallurgy-fluid",
  },
}
)