data:extend(
{
  {
    type = "fluid",
    name = "molten-tin",
    default_temperature = 400,
    max_temperature = 400,
    heat_capacity = "0KJ",
    base_color = {r=214, g=165, b=91},
    flow_color = {r=214, g=165, b=91},
    icon = "__DyTech-Graphics__/graphics/fluid/molten-tin.png",
    order = "tin",
    pressure_to_speed_ratio = 0.2,
    flow_to_energy_ratio = 0.295,
    subgroup = "metallurgy-fluid-metal-basic",
  },
  {
    type = "fluid",
    name = "molten-zinc",
    default_temperature = 500,
    max_temperature = 500,
    heat_capacity = "0KJ",
    base_color = {r=214, g=165, b=91},
    flow_color = {r=214, g=165, b=91},
    icon = "__DyTech-Graphics__/graphics/fluid/molten-zinc.png",
    order = "zinc",
    pressure_to_speed_ratio = 0.2,
    flow_to_energy_ratio = 0.295,
    subgroup = "metallurgy-fluid-metal-basic",
  },
  {
    type = "fluid",
    name = "molten-lead",
    default_temperature = 400,
    max_temperature = 400,
    heat_capacity = "0KJ",
    base_color = {r=214, g=165, b=91},
    flow_color = {r=214, g=165, b=91},
    icon = "__DyTech-Graphics__/graphics/fluid/molten-lead.png",
    order = "lead",
    pressure_to_speed_ratio = 0.2,
    flow_to_energy_ratio = 0.295,
    subgroup = "metallurgy-fluid-metal-basic",
  },
  {
    type = "fluid",
    name = "molten-silver",
    default_temperature = 2200,
    max_temperature = 2200,
    heat_capacity = "0KJ",
    base_color = {r=214, g=165, b=91},
    flow_color = {r=214, g=165, b=91},
    icon = "__DyTech-Graphics__/graphics/fluid/molten-silver.png",
    order = "silver",
    pressure_to_speed_ratio = 0.2,
    flow_to_energy_ratio = 0.295,
    subgroup = "metallurgy-fluid-metal-basic",
  },
  {
    type = "fluid",
    name = "molten-gold",
    default_temperature = 1100,
    max_temperature = 1100,
    heat_capacity = "0KJ",
    base_color = {r=214, g=165, b=91},
    flow_color = {r=214, g=165, b=91},
    icon = "__DyTech-Graphics__/graphics/fluid/molten-gold.png",
    order = "gold",
    pressure_to_speed_ratio = 0.2,
    flow_to_energy_ratio = 0.295,
    subgroup = "metallurgy-fluid-metal-basic",
  },
  {
    type = "fluid",
    name = "molten-tungsten",
    default_temperature = 3500,
    max_temperature = 3500,
    heat_capacity = "0KJ",
    base_color = {r=214, g=165, b=91},
    flow_color = {r=214, g=165, b=91},
    icon = "__DyTech-Graphics__/graphics/fluid/molten-tungsten.png",
    order = "tungsten",
    pressure_to_speed_ratio = 0.2,
    flow_to_energy_ratio = 0.295,
    subgroup = "metallurgy-fluid-metal-basic",
  },
}
)