module("database")

--  [""]={},
--to add to craftitems
--  [""]={resource=1},
--to add to mineitems

--[[CRAFTED ITEMS]]--

craftitems =
{
	-- Base Game Items --
	["wood"]={resource=0.5},
	["wooden-chest"]={["wood"]=4, chest=1},
	["iron-stick"]={plates=0.5, tech=0.5},
	["iron-axe"]={plates=3, mining=1, ["iron-stick"]=2},
	["stone-furnace"]={resource=5, machine=1},
	["boiler"]={["stone-furnace"]=1, ["pipe"]=1, machine=1, energy=1},
	["steam-engine"]={["iron-gear-wheel"]=5, ["pipe"]=5, plates=5, machine=1, energy=1},
	["iron-gear-wheel"]={plates=2, gear=1},
	["electronic-circuit"]={plates=1, tech=1, ["copper-cable"]=3},
	["basic-transport-belt"]={plates=1, ["iron-gear-wheel"]=1, belt=1},
	["basic-mining-drill"]={["electronic-circuit"]=3, ["iron-gear-wheel"]=5, plates=10, mining=2, machine=1},
	["burner-mining-drill"]={["iron-gear-wheel"]=3, ["stone-furnace"]=1, plates=3, mining=1, machine=1},
	["basic-inserter"]={["electronic-circuit"]=1, ["iron-gear-wheel"]=1, plates=1, inserter=1},
	["burner-inserter"]={plates=1, ["iron-gear-wheel"]=1, inserter=1},
	["pipe"]={plates=1, tech=1},
	["offshore-pump"]={["electronic-circuit"]=2, ["pipe"]=1, ["iron-gear-wheel"]=1, machine=1},
	["copper-cable"]={plates=0.5, tech=0.5},
	["small-electric-pole"]={["wood"]=2, ["copper-cable"]=2, energy=1},
	["pistol"]={plates=10, gun=1},
	["submachine-gun"]={gun=1, ["iron-gear-wheel"]=10, plates=15},
	["basic-bullet-magazine"]={ammo=1, plates=2},
	["basic-armor"]={armor=1, plates=40},
	["radar"]={machine=1, ["electronic-circuit"]=5, ["iron-gear-wheel"]=5, plates=10},
	["small-lamp"]={["electronic-circuit"]=1, ["iron-stick"]=3, plates=1, machine=1, energy=1},
	["pipe-to-ground"]={["pipe"]=10, plates=5, tech=1},
	["assembling-machine-1"]={["electronic-circuit"]=3, ["iron-gear-wheel"]=5, plates=9, machine=1},
	["repair-pack"]={["electronic-circuit"]=1, ["iron-gear-wheel"]=1, tech=1},
	["piercing-bullet-magazine"]={ammo=1, plates=6},
	["rocket"]={["electronic-circuit"]=1, ["explosives"]=2, plates=2, ammo=1},
	["explosive-rocket"]={["rocket"]=1, ["explosives"]=5, ammo=1},
	["shotgun-shell"]={ammo=1, plates=4},
	["piercing-shotgun-shell"]={ammo=1, plates=4},
	["railgun-dart"]={ammo=1, plates=5, ["electronic-circuit"]=5},
	["poison-capsule"]={plates=3, capsule=1, ["electronic-circuit"]=3, resource=10},
	["slowdown-capsule"]={plates=2, capsule=1, ["electronic-circuit"]=2, resource=5},
	["basic-grenade"]={plates=5, resource=10, capsule=1},
	["defender-capsule"]={capsule=1, ["piercing-bullet-magazine"]=1, ["electronic-circuit"]=2, ["iron-gear-wheel"]=3},
	["distractor-capsule"]={capsule=5, ["defender-capsule"]=4, ["advanced-circuit"]=3},
	["destroyer-capsule"]={capsule=5, ["distractor-capsule"]=4, ["speed-module"]=1},
	["basic-electric-discharge-defense-remote"]={capsule=1, ["electronic-circuit"]=1},
	["plastic-bar"]={resource=4, tech=1},
	["night-vision-equipment"]={armor=1, ["advanced-circuit"]=5, plates=10},
	["energy-shield-equipment"]={armor=1, ["advanced-circuit"]=5, plates=10},
	["energy-shield-mk2-equipment"]={armor=1, ["energy-shield-equipment"]=10, ["processing-unit"]=10},
	["battery-equipment"]={armor=1, ["battery"]=5, plates=10},
	["battery-mk2-equipment"]={armor=1, ["battery-equipment"]=10, ["processing-unit"]=20},
	["solar-panel-equipment"]={armor=1, ["solar-panel"]=5, ["processing-unit"]=1, plates=5},
	["fusion-reactor-equipment"]={armor=1, ["processing-unit"]=100, alien=30},
	["basic-laser-defense-equipment"]={armor=1, ["processing-unit"]=1, plates=5, ["laser-turret"]=5},
	["basic-electric-discharge-defense-equipment"]={armor=1, ["processing-unit"]=5, plates=20, ["laser-turret"]=10},
	["basic-exoskeleton-equipment"]={armor=1, ["processing-unit"]=10, plates=20, ["electric-engine-unit"]=30},
	["gun-turret"]={turret=1, ["iron-gear-wheel"]=5, plates=15},
	["laser-turret"]={turret=2, ["electronic-circuit"]=5, ["battery"]=3, plates=5},
	["speed-module"]={["advanced-circuit"]=5, ["processing-unit"]=5, modules=1},
	["speed-module-2"]={["speed-module"]=4, ["advanced-circuit"]=5, ["processing-unit"]=5, modules=1},
	["speed-module-3"]={["speed-module-2"]=5, ["advanced-circuit"]=5, ["processing-unit"]=5, alien=1, modules=1},
	["effectivity-module"]={["advanced-circuit"]=5, ["processing-unit"]=5, modules=1},
	["effectivity-module-2"]={["effectivity-module"]=4, ["advanced-circuit"]=5, ["processing-unit"]=5, modules=1},
	["effectivity-module-3"]={["effectivity-module-2"]=5, ["advanced-circuit"]=5, ["processing-unit"]=5, alien=1, modules=1},
	["productivity-module"]={["advanced-circuit"]=5, ["processing-unit"]=5, modules=1},
	["productivity-module-2"]={["productivity-module"]=4, ["advanced-circuit"]=5, ["processing-unit"]=5, modules=1},
	["productivity-module-3"]={["productivity-module-2"]=5, ["advanced-circuit"]=5, ["processing-unit"]=5, alien=1, modules=1},
	["long-handed-inserter"]={inserter=1, ["iron-gear-wheel"]=1, plates=1, ["basic-inserter"]=1},
	["fast-inserter"]={inserter=1, ["electronic-circuit"]=2, plates=2, ["basic-inserter"]=1},
	["smart-inserter"]={inserter=1, ["fast-inserter"]=1, ["electronic-circuit"]=4},
	["player-port"]={["electronic-circuit"]=10, ["iron-gear-wheel"]=5, plates=1, machine=1},
	["fast-transport-belt"]={belt=1, ["iron-gear-wheel"]=5, ["basic-transport-belt"]=1},
	["express-transport-belt"]={belt=1, ["iron-gear-wheel"]=5, ["fast-transport-belt"]=1},
	["solar-panel"]={energy=3, plates=10, ["electronic-circuit"]=15, machine=1},
	["assembling-machine-2"]={plates=9, ["iron-gear-wheel"]=5, ["electronic-circuit"]=3, ["assembling-machine-1"]=1, machine=1},
	["assembling-machine-3"]={["speed-module"]=4, ["assembling-machine-2"]=2, machine=1},
	["car"]={["engine-unit"]=8, plates=25},
	["straight-rail"]={["iron-stick"]=1, plates=1, resource=1},
	["curved-rail"]={["iron-stick"]=4, plates=4, resource=4},
	["diesel-locomotive"]={["engine-unit"]=15, ["electronic-circuit"]=5, plates=10},
	["cargo-wagon"]={["iron-gear-wheel"]=10, plates=25},
	["train-stop"]={["electronic-circuit"]=5, plates=13},
	["rail-signal"]={["electronic-circuit"]=1, plates=5},
	["heavy-armor"]={armor=2, plates=150},
	["basic-modular-armor"]={["advanced-circuit"]=30, ["processing-unit"]=5, plates=50},
	["power-armor"]={armor=8, ["processing-unit"]=100, ["electric-engine-unit"]=30, plates=100, alien=10},
	["power-armor-mk2"]={armor=16, ["effectivity-module-3"]=5, ["speed-module-3"]=5, ["processing-unit"]=200, plates=50, alien=50},
	["iron-chest"]={chest=1, plates=8},
	["steel-chest"]={chest=1, plates=8},
	["smart-chest"]={chest=1, ["electronic-circuit"]=3, ["steel-chest"]=1},
	["wall"]={wall=1, resource=5},
	["land-mine"]={ammo=1, plates=1, ["explosives"]=2},
	["flame-thrower"]={gun=1, plates=5, ["iron-gear-wheel"]=10},
	["rocket-launcher"]={gun=1, plates=5, ["iron-gear-wheel"]=5, ["electronic-circuit"]=5},
	["shotgun"]={gun=1, plates=25, ["iron-gear-wheel"]=5, ["wood"]=5},
	["combat-shotgun"]={gun=1, plates=25, ["iron-gear-wheel"]=5, [""]=10},
	["railgun"]={gun=1, plates=30, ["advanced-circuit"]=10, ["electronic-circuit"]=5},
	["science-pack-1"]={science=1, plates=1, ["iron-gear-wheel"]=1},
	["science-pack-2"]={science=2, ["basic-inserter"]=1, ["basic-transport-belt"]=1},
	["science-pack-3"]={science=3, ["battery"]=1, ["advanced-circuit"]=1, ["smart-inserter"]=1, plates=1},
	["alien-science-pack"]={science=4, alien=1},
	["lab"]={["electronic-circuit"]=10, ["iron-gear-wheel"]=10, ["basic-transport-belt"]=4, machine=1},
	["red-wire"]={["electronic-circuit"]=1, ["copper-cable"]=1},
	["green-wire"]={["electronic-circuit"]=1, ["copper-cable"]=1},
	["basic-transport-belt-to-ground"]={["basic-transport-belt"]=5, plates=10},
	["fast-transport-belt-to-ground"]={["iron-gear-wheel"]=20, ["basic-transport-belt-to-ground"]=2},
	["express-transport-belt-to-ground"]={["iron-gear-wheel"]=40, ["fast-transport-belt-to-ground"]=2},
	["basic-splitter"]={["electronic-circuit"]=5, plates=5, ["basic-transport-belt"]=4},
	["fast-splitter"]={["electronic-circuit"]=10, ["iron-gear-wheel"]=10, ["fast-transport-belt"]=4},
	["express-splitter"]={["advanced-circuit"]=10, ["iron-gear-wheel"]=10, ["express-transport-belt"]=4},
	["advanced-circuit"]={["electronic-circuit"]=2, ["plastic-bar"]=2, ["copper-cable"]=4},
	["processing-unit"]={["electronic-circuit"]=20, ["advanced-circuit"]=2},
	["logistic-robot"]={robot=1, ["flying-robot-frame"]=1, ["advanced-circuit"]=2},
	["construction-robot"]={robot=1, ["flying-robot-frame"]=1, ["electronic-circuit"]=2},
	["logistic-chest-passive-provider"]={robot=1, ["smart-chest"]=1, ["advanced-circuit"]=1},
	["logistic-chest-active-provider"]={robot=1, ["smart-chest"]=1, ["advanced-circuit"]=1},
	["logistic-chest-requester"]={robot=1, ["smart-chest"]=1, ["advanced-circuit"]=1},
	["logistic-chest-storage"]={robot=1, ["smart-chest"]=1, ["advanced-circuit"]=1},
	["rocket-defense"]={["rocket"]=100, ["advanced-circuit"]=128, ["processing-unit"]=128, ["speed-module-3"]=50, ["productivity-module-3"]=50},
	["roboport"]={robot=5, plates=45, ["iron-gear-wheel"]=45, ["advanced-circuit"]=45, machine=1},
	["steel-axe"]={plates=5, mining=1, ["iron-stick"]=2},
	["big-electric-pole"]={energy=1, plates=10},
	["substation"]={energy=5, plates=15, ["advanced-circuit"]=5},
	["medium-electric-pole"]={energy=1, plates=4},
	["basic-accumulator"]={energy=25, plates=2, ["battery"]=5},
	["steel-furnace"]={energy=1, plates=8, machine=1, resource=10},
	["electric-furnace"]={energy=3, plates=15, resource=10, ["advanced-circuit"]=5, machine=1},
	["basic-beacon"]={["electronic-circuit"]=20, ["advanced-circuit"]=20, plates=10, ["copper-cable"]=10, machine=1},
	["blueprint"]={["advanced-circuit"]=1},
	["deconstruction-planner"]={["advanced-circuit"]=1},
	["pumpjack"]={machine=1, plates=15, ["iron-gear-wheel"]=10, ["electronic-circuit"]=10, ["pipe"]=10},
	["oil-refinery"]={machine=1, plates=15, resource=10, ["iron-gear-wheel"]=10, ["electronic-circuit"]=10, ["pipe"]=10},
	["engine-unit"]={plates=1, ["iron-gear-wheel"]=1, ["pipe"]=2},
	["electric-engine-unit"]={["engine-unit"]=1, ["electronic-circuit"]=2},
	["flying-robot-frame"]={["electric-engine-unit"]=1, ["battery"]=2, plates=1, ["electronic-circuit"]=3},
	["explosives"]={resource=2},
	["battery"]={plates=2, tech=1},
	["storage-tank"]={machine=1, plates=25},
	["small-pump"]={["electric-engine-unit"]=1, ["pipe"]=1, plates=1, machine=1},
	["chemical-plant"]={plates=5, ["pipe"]=5, ["iron-gear-wheel"]=5, ["electronic-circuit"]=5, machine=1},
	["small-plane"]={["plastic-bar"]=120, ["advanced-circuit"]=250, ["electric-engine-unit"]=20, ["battery"]=150},
	-- DyTech Core --
	-- DyTech Compatibility --
	-- DyTech Dynamic --
	-- DyTech Energy --
	-- DyTech Gems --
	-- DyTech Inserters --
	["inserter-half"]={inserter=1, ["electronic-circuit"]=1, ["iron-gear-wheel"]=1, plates=1},
	["inserter-long"]={inserter=2, plates=2, ["basic-inserter"]=1, ["electronic-circuit"]=2},
	["inserter-half-long"]={inserter=2, plates=2, ["basic-inserter"]=1, ["electronic-circuit"]=2},
	["inserter-fast-half"]={inserter=2, plates=2, ["basic-inserter"]=1, ["electronic-circuit"]=2},
	["inserter-veryfast"]={inserter=2, plates=2, ["basic-inserter"]=1, ["electronic-circuit"]=2},
	["inserter-veryfast-half"]={inserter=2, plates=2, ["basic-inserter"]=1, ["electronic-circuit"]=2},
	["inserter-half-filter"]={inserter=3, plates=1, ["inserter-half"]=1, ["advanced-circuit"]=1},
	["inserter-long-filter"]={inserter=3, plates=1, ["inserter-long"]=1, ["advanced-circuit"]=2},
	["inserter-long-half-filter"]={inserter=3, plates=1, ["inserter-long"]=1, ["advanced-circuit"]=2},
	["inserter-fast-half-filter"]={inserter=3, plates=1, ["inserter-long"]=1, ["advanced-circuit"]=2},
	["inserter-veryfast-filter"]={inserter=3, plates=1, ["inserter-long"]=1, ["advanced-circuit"]=2},
	["inserter-veryfast-half-filter"]={inserter=3, plates=1, ["inserter-long"]=1, ["advanced-circuit"]=2},
	["inserter-half-smart"]={inserter=4, ["processing-unit"]=6, ["inserter-half-filter"]=1, plates=15},
	["inserter-long-smart"]={inserter=4, ["processing-unit"]=8, ["inserter-long-filter"]=1, plates=15},
	["inserter-long-half-smart"]={inserter=4, ["processing-unit"]=8, ["inserter-long-filter"]=1, plates=15},
	["inserter-fast-half-smart"]={inserter=4, ["processing-unit"]=10, ["inserter-long-filter"]=1, plates=15},
	["inserter-veryfast-smart"]={inserter=4, ["processing-unit"]=10, ["inserter-long-filter"]=1, plates=15},
	["inserter-veryfast-half-smart"]={inserter=4, ["processing-unit"]=10, ["inserter-long-filter"]=1, plates=15},
	["dytech-inserter"]={inserter=5, ["iron-gear-wheel"]=10, ["circuit3"]=10, plates=10},
	["dytech-inserter-fast"]={inserter=6, ["circuit3"]=25, ["steel-gear-wheel"]=25, plates=15},
	["long-handed-inserter-filter"]={inserter=1, ["iron-gear-wheel"]=1, ["advanced-circuit"]=2, ["basic-inserter"]=1, plates=1}
	-- DyTech Logistic --
	-- DyTech Metallurgy --
	-- DyTech Meteors --
	-- DyTech Mining --
	-- DyTech Modules --
	-- DyTech Storage --
	-- DyTech Tools --
	-- DyTech Transportation --
	-- DyTech Warfare --
}

--[[MINED ITEMS]]--

mineitems =
{
	["sand"]={resource=1},
	["coal"]={resource=1},
	["stone"]={resource=1},
	["iron-ore"]={resource=1},
	["copper-ore"]={resource=1},
	["gold-ore"]={resource=1},
	["silver-ore"]={resource=1},
	["zinc-ore"]={resource=1},
	["tungsten-ore"]={resource=1},
	["tin-ore"]={resource=1},
	["raw-wood"]={resource=1},
	["ruby-ore"]={gems=5},
	["sapphire-ore"]={gems=5},
	["diamond-ore"]={gems=5},
	["topaz-ore"]={gems=5},
	["emerald-ore"]={gems=5},
	["ruby-orex"]={gems=1},
	["sapphire-orex"]={gems=1},
	["diamond-orex"]={gems=1},
	["topaz-orex"]={gems=1},
	["emerald-orex"]={gems=1}
}

--[[KILLED ENTITIES]]--

kill =
{
	["small-biter"]={small=1},
	["medium-biter"]={medium=1},
	["big-biter"]={big=1},
	["berserker-biter"]={berserker=1},
	["elder-biter"]={elder=1},
	["king-biter"]={king=1},
	["queen-biter"]={queen=1}
}

--[[Meteor spawns]]--

meteor = 
{ 
	["meteor-small-1"]={small=1},
	["meteor-small-2"]={small=1},
	["meteor-small-3"]={small=1},
	["meteor-small-4"]={small=1},
	["meteor-small-5"]={small=1},
	["meteor-medium-1"]={medium=1},
	["meteor-medium-2"]={medium=1},
	["meteor-medium-3"]={medium=1},
	["meteor-medium-4"]={medium=1},
	["meteor-medium-5"]={medium=1},
	["meteor-large-1"]={large=1},
	["meteor-large-2"]={large=1},
	["meteor-large-3"]={large=1},
	["meteor-large-4"]={large=1},
	["meteor-large-5"]={large=1},
	["meteor-comet-1"]={comet=1},
	["meteor-comet-2"]={comet=1},
	["meteor-comet-3"]={comet=1},
	["meteor-comet-4"]={comet=1},
	["meteor-comet-5"]={comet=1},
	["meteor-asteroid-1"]={asteroid=1}
}