data:extend(
{
  {
	type= "item",
	name= "centrifuge",
	icon = "__base__/graphics/icons/assembling-machine-3.png",
	flags= {"goes-to-quickbar"},
	order= "a[centrifuge-mk1]",
	subgroup = "metallurgy-machines",
	place_result= "centrifuge",
	stack_size= 10,
  },
  {
	type= "item",
	name= "centrifuge-mk2",
	icon = "__base__/graphics/icons/assembling-machine-3.png",
	flags= {"goes-to-quickbar"},
	order= "a[centrifuge-mk2]",
	subgroup = "metallurgy-machines",
	place_result= "centrifuge-mk2",
	stack_size= 10,
  },
  {
	type= "item",
	name= "centrifuge-mk3",
	icon = "__base__/graphics/icons/assembling-machine-3.png",
	flags= {"goes-to-quickbar"},
	order= "a[centrifuge-mk3]",
	subgroup = "metallurgy-machines",
	place_result= "centrifuge-mk3",
	stack_size= 10,
  },
  {
	type= "item",
	name= "centrifuge-mk4",
	icon = "__base__/graphics/icons/assembling-machine-3.png",
	flags= {"goes-to-quickbar"},
	order= "a[centrifuge-mk4]",
	subgroup = "metallurgy-machines",
	place_result= "centrifuge-mk4",
	stack_size= 10,
  },
  {
	type= "item",
	name= "centrifuge-mk5",
	icon = "__base__/graphics/icons/assembling-machine-3.png",
	flags= {"goes-to-quickbar"},
	order= "a[centrifuge-mk5]",
	subgroup = "metallurgy-machines",
	place_result= "centrifuge-mk5",
	stack_size= 10,
  },
}
)
