data:extend(
{
  {
    type = "container",
    name = "pollution-creator-1",
    icon = "__DyTech-Graphics__/graphics/icons/pollution-11.png",
    flags = {"placeable-player", "player-creation"},
	emissions_per_tick = 2,
    minable = {
		mining_particle = "wooden-particle",
		mining_time = 1,
		result = "pollution-creator-1",
    },
    max_health = 10,
    collision_box = {{-0.4, -0.4}, {0.4, 0.4}},
    selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	inventory_size = 1,
    picture ={
        filename = "__DyTech-Graphics__/graphics/entity/pollution/pollution-11.png",
        priority = "extra-high",
        width = 32,
        height = 32,
    },
  },
  {
    type = "container",
    name = "pollution-uncreator-1",
    icon = "__DyTech-Graphics__/graphics/icons/pollution-01.png",
    flags = {"placeable-player", "player-creation"},
	emissions_per_tick = -2,
    minable = {
		mining_particle = "wooden-particle",
		mining_time = 1,
		result = "pollution-uncreator-1",
    },
    max_health = 10,
    collision_box = {{-0.4, -0.4}, {0.4, 0.4}},
    selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	inventory_size = 1,
    picture ={
        filename = "__DyTech-Graphics__/graphics/entity/pollution/pollution-01.png",
        priority = "extra-high",
        width = 32,
        height = 32,
    },
  },
  {
    type = "container",
    name = "pollution-creator-2",
    icon = "__DyTech-Graphics__/graphics/icons/pollution-12.png",
    flags = {"placeable-player", "player-creation"},
	emissions_per_tick = 4,
    minable = {
		mining_particle = "wooden-particle",
		mining_time = 1,
		result = "pollution-creator-2",
    },
    max_health = 10,
    collision_box = {{-0.4, -0.4}, {0.4, 0.4}},
    selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	inventory_size = 1,
    picture ={
        filename = "__DyTech-Graphics__/graphics/entity/pollution/pollution-12.png",
        priority = "extra-high",
        width = 32,
        height = 32,
    },
  },
  {
    type = "container",
    name = "pollution-uncreator-2",
    icon = "__DyTech-Graphics__/graphics/icons/pollution-02.png",
    flags = {"placeable-player", "player-creation"},
	emissions_per_tick = -4,
    minable = {
		mining_particle = "wooden-particle",
		mining_time = 1,
		result = "pollution-uncreator-2",
    },
    max_health = 10,
    collision_box = {{-0.4, -0.4}, {0.4, 0.4}},
    selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	inventory_size = 1,
    picture ={
        filename = "__DyTech-Graphics__/graphics/entity/pollution/pollution-02.png",
        priority = "extra-high",
        width = 32,
        height = 32,
    },
  },
  {
    type = "container",
    name = "pollution-creator-3",
    icon = "__DyTech-Graphics__/graphics/icons/pollution-13.png",
    flags = {"placeable-player", "player-creation"},
	emissions_per_tick = 8,
    minable = {
		mining_particle = "wooden-particle",
		mining_time = 1,
		result = "pollution-creator-3",
    },
    max_health = 10,
    collision_box = {{-0.4, -0.4}, {0.4, 0.4}},
    selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	inventory_size = 1,
    picture ={
        filename = "__DyTech-Graphics__/graphics/entity/pollution/pollution-13.png",
        priority = "extra-high",
        width = 32,
        height = 32,
    },
  },
  {
    type = "container",
    name = "pollution-uncreator-3",
    icon = "__DyTech-Graphics__/graphics/icons/pollution-03.png",
    flags = {"placeable-player", "player-creation"},
	emissions_per_tick = -8,
    minable = {
		mining_particle = "wooden-particle",
		mining_time = 1,
		result = "pollution-uncreator-3",
    },
    max_health = 10,
    collision_box = {{-0.4, -0.4}, {0.4, 0.4}},
    selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	inventory_size = 1,
    picture ={
        filename = "__DyTech-Graphics__/graphics/entity/pollution/pollution-03.png",
        priority = "extra-high",
        width = 32,
        height = 32,
    },
  },
  {
    type = "container",
    name = "pollution-creator-4",
    icon = "__DyTech-Graphics__/graphics/icons/pollution-14.png",
    flags = {"placeable-player", "player-creation"},
	emissions_per_tick = 16,
    minable = {
		mining_particle = "wooden-particle",
		mining_time = 1,
		result = "pollution-creator-4",
    },
    max_health = 10,
    collision_box = {{-0.4, -0.4}, {0.4, 0.4}},
    selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	inventory_size = 1,
    picture ={
        filename = "__DyTech-Graphics__/graphics/entity/pollution/pollution-14.png",
        priority = "extra-high",
        width = 32,
        height = 32,
    },
  },
  {
    type = "container",
    name = "pollution-uncreator-4",
    icon = "__DyTech-Graphics__/graphics/icons/pollution-04.png",
    flags = {"placeable-player", "player-creation"},
	emissions_per_tick = -16,
    minable = {
		mining_particle = "wooden-particle",
		mining_time = 1,
		result = "pollution-uncreator-4",
    },
    max_health = 10,
    collision_box = {{-0.4, -0.4}, {0.4, 0.4}},
    selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	inventory_size = 1,
    picture ={
        filename = "__DyTech-Graphics__/graphics/entity/pollution/pollution-04.png",
        priority = "extra-high",
        width = 32,
        height = 32,
    },
  },
  {
    type = "container",
    name = "pollution-creator-5",
    icon = "__DyTech-Graphics__/graphics/icons/pollution-15.png",
    flags = {"placeable-player", "player-creation"},
	emissions_per_tick = 32,
    minable = {
		mining_particle = "wooden-particle",
		mining_time = 1,
		result = "pollution-creator-5",
    },
    max_health = 10,
    collision_box = {{-0.4, -0.4}, {0.4, 0.4}},
    selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	inventory_size = 1,
    picture ={
        filename = "__DyTech-Graphics__/graphics/entity/pollution/pollution-15.png",
        priority = "extra-high",
        width = 32,
        height = 32,
    },
  },
  {
    type = "container",
    name = "pollution-uncreator-5",
    icon = "__DyTech-Graphics__/graphics/icons/pollution-05.png",
    flags = {"placeable-player", "player-creation"},
	emissions_per_tick = -32,
    minable = {
		mining_particle = "wooden-particle",
		mining_time = 1,
		result = "pollution-uncreator-5",
    },
    max_health = 10,
    collision_box = {{-0.4, -0.4}, {0.4, 0.4}},
    selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	inventory_size = 1,
    picture ={
        filename = "__DyTech-Graphics__/graphics/entity/pollution/pollution-05.png",
        priority = "extra-high",
        width = 32,
        height = 32,
    },
  },
}
)